### ISSUE TITLE
asciidoctor: FAILED: '/github/workspace/configs/config.rb' could not be loaded 

### ISSUE THREAD

**Issue by TheOpsMgr** [Analog-inc/asciidoctor-action#1]
I've tried setting up the action using the examples provided inc the asciidoc.sh file but I get the error 

asciidoctor: FAILED: '/github/workspace/configs/config.rb' could not be loaded

I will try and add an empty file config.rb to the repo but I'd like to understand the config it's expecting to find?

**Comment by ledoyen** [comment]
@TheOpsMgr the example `asciidoc.sh` is just a little buggy.

To make the asciidoc-pdf official sample works, I had to:
* remove the `-r ${CURRENT_PATH}/configs/config.rb` at l.26 that made the pdf generation failed
* create the `./themes` directory that is missing
* uncomment the lines (l.11-12) about copying themes and fonts

**Comment by eroccowaruico** [comment]
thank you
For more advanced use guide
[Analog-inc/asciidoctor-action-sample](https://github.com/Analog-inc/asciidoctor-action-sample)
